### PR TITLE
minor updates

### PR DESCRIPTION
**Pull request by shobhit15082003**
1) Added emergency contact in patient
2)Added years of experience in doctor
3)Added is available in doctor which automatically becomes true when a doctor logs in which makes him available for the day and when logs out makes him unavailable.
4) Addition of nurse and lab assistant 
5) Added middlewares

### CODE REVIEW

**Review by yalsik86 — CHANGES_REQUESTED** [review]
in backend/models/Doctor.js
correct "tyep"
to "type"

**Comment by shobhit15082003** [comment]
fixed
@yalsik86

**Comment by yalsik86** [comment]
Nurse and Lab Assistant not required as of now, get rid of it

**Comment by shobhit15082003** [comment]
@yalsik86 done

**Review by yalsik86 — APPROVED** [review]

**Pull request merged**
